# local/default

# "custom": configuration section with not Spring Boot common application properties
# see https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
custom:
  app:
    security:
      # if not enabled, everyone can add manifests and add button will be shown
      enabled: true
      username: foobar
      password: hamspam
  iiif:
    graciousParsing: true
  mongeez:
    classpathToMongeezXml: '/de/digitalcollections/iiif/bookshelf/config/mongeez/mongeez.xml'
    dbName: 'iiif-bookshelf'
  solr:
    collection: 'bookshelf'
  summary:
    thumbnail:
      width: 280
# end of custom configuration section

info:
  app:
    encoding: @project.build.sourceEncoding@
    java:
      source: @maven.compiler.source@
      target: @maven.compiler.target@
    project:
      name: '@project.name@'
      version: @project.version@
      buildDetails: '@versionName@'

management:
  endpoints:
    web:
      base-path: '/monitoring'
      exposure:
        include: '*'
  info:
    git:
      mode: full
  server:
    port: 8081

server:
  port: 8080
  server-header: '@project.name@ v@project.version@'

spring:
  data:
    mongodb:
      uri: mongodb://localhost:20202/iiif-bookshelf
    solr:
      # collection name see custom-section
      host: 'http://127.0.0.1:21212/solr'
      # Solr host. Ignored if "zk-host" is set.
#      repositories:
#        enabled: true
        # Enable Solr repositories.
#      zk-host: ''
      # ZooKeeper host address in the form HOST:PORT.
  messages:
    basename: 'messages, messages-commons'
    cache-duration: 5
    encoding: 'UTF-8'
    fallback-to-system-locale: false
  profiles:
    active: local
  security:
    user:
      name: admin
      password: secret
      roles: ACTUATOR
  thymeleaf:
    cache: false
    mode: HTML

---

management:
  server:
    port: 9001

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/iiif-bookshelf
    solr:
      host: 'http://127.0.0.1:8983/solr'
      # Solr host. Ignored if "zk-host" is set.
#      repositories:
#        enabled: true
        # Enable Solr repositories.
#      zk-host: ''
      # ZooKeeper host address in the form HOST:PORT.
  profiles: PROD
  thymeleaf:
    cache: true