# "custom": configuration section with not Spring Boot common application properties
# see https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
custom:
  app:
    security:
      enabled: true
      username: foobar
      password: hamspam
  iiif:
    graciousParsing: false
  mongeez:
    classpathToMongeezXml: '/de/digitalcollections/iiif/bookshelf/config/mongeez/mongeez.xml'
    dbName: 'iiif-bookshelf'
  solr:
    collection: 'bookshelf'
# end of custom configuration section

endpoints:
  hypermedia:
    enabled: true

info:
  app:
    encoding: @project.build.sourceEncoding@
    java:
      source: @maven.compiler.source@
      target: @maven.compiler.target@
    project:
      name: '@project.name@'
      groupId: @project.groupId@
      artifactId: @project.artifactId@
      version: @project.version@

management:
  context-path: '/monitoring'
  port: 8081
  security:
    enabled: true
    roles: 'ACTUATOR, USER'
    # ACTUATOR is default, but we add USER as workaround for not working application.yml name/password

security:
  headers:
    cache: false
  user:
    name: admin
    password: secret

server:
  port: 8080
  server-header: '@project.name@ v@project.version@'

spring:
  data:
    mongodb:
      uri: mongodb://localhost:20202/iiif-bookshelf
    solr:
      # collection name see custom-section
      host: 'http://127.0.0.1:21212/solr'
      # Solr host. Ignored if "zk-host" is set.
#      repositories:
#        enabled: true
        # Enable Solr repositories.
#      zk-host: ''
      # ZooKeeper host address in the form HOST:PORT.
  profiles:
    active: local
  thymeleaf:
    cache: false
    mode: HTML

---

custom:
  app:
    security:
      enabled: true
      username: mdz
      password: Hopfenzeitung

management:
  port: 9001
  security:
    enabled: true

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/iiif-bookshelf
    solr:
      host: 'http://127.0.0.1:8983/solr'
      # Solr host. Ignored if "zk-host" is set.
#      repositories:
#        enabled: true
        # Enable Solr repositories.
#      zk-host: ''
      # ZooKeeper host address in the form HOST:PORT.
  profiles: PROD
  thymeleaf:
    cache: true